version: "3"
services:
  uaa:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgresql
      DB_ENV_DB: postgres
      DB_ENV_USER: postgres
      DB_ENV_PASS: postgres
      UAA_HOST: localhost
      UAA_PORT: 8080
      UAA_BASEURL: http://localhost:8080/uaa
      UAA_ADMIN_SECRET: adminsecret
      DB_PORT_5432_TCP_ADDR: db
      DB_PORT_5432_TCP_PORT: 5432

  db:
    image: postgres
    ports:
      - "8001:5432"
    environment:
      POSTGRES_DB: uaadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
